travis:
  secure:
    BINSTAR_TOKEN: z3Lzz+WTPmQ+bsJvPh4Kt4PSrjQnNJHgIZapr0D+0ahzYkkpG434beP2JH3zOm8nVXm0OwwwudXK6b37cpBfoSl8qqX2q4pNEVWqzlZCLH7ubjB2R5M1heXB/pDJKNjD80mG/K12fxm208V/nc+m+B8MG2IgyPqkd17rXCIn6aifHXaQEZ4csszD2/JWLHlYpmN3k6UT6PlAbJAnJedU4oMmglFGPGJbuGrReuHTzKrMrsELbsrY0FkFnjn3/Yp7dulZIYpSUDiUlrgc6nqBWVSJH8hFb6L6QN8TlGZjrn4+HmgcJ2AGBORfd6gMAZ5n66yYqx2nSfs1y2ZRzox81oB/tu6qdBjcFJrMdKyauBhfJDAvZKyBkezquF80bU6w/iTn0hVPT/XUkCfmINtVsEdl2usrfJbh7IGcbJu0NmUk9p7PyjjJ6u4xNj6sL4XxEU6ctbWfvAarh6PoMOu1kCDzq8SvuVUzEYSL3Dh7BuFf4Gr99Nu0UGnZdjqMMIa3jsXKeveFykU1nqsKe3T3CGr6pkHB/YFZu2DIFC2LbllMgD/5KSZJ1boA4rK00/1VKX+WanymfMslHJd8SKFBBfErTyFja9a8+ji4AV4k+h4LY52SONQ0YiR5wM5FFHC2LPwKUiGjP94o4IiyNlPUwxltJykxC5oHDuSnHEOWVd8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
