travis:
  secure:
    BINSTAR_TOKEN: Klc88nhL+Lv5lFM4Pn/X47uY/RD8Qj5fK+cCpmZJiFtiOnGO0yGEFAhyjN+GNyMdDZiEeziM/o3OXvHMYmvp9fOjKIWDe9RvzuqmY5nYbfjJmV7Fr/LklV6mgufEmEzzO3Mhs4dfMlbERLCQvPjHYQm3EigMd5x7gyw85+63ygSykmtY8ciViljplm6ObhbK45ofRBGxuVK9X5njmT0LEuznsxyOoMOLTn2hPQRlZWRSMU1gDHDPw6s/knzArXvlHVWz8y5IeNywpEt3AN2Fooypu1KFhYVVIJb7Z1vqKMZK3h7GMv/DLjWF0XtQBl4n97xy4j1Pt4jJ8OprXQ/VYpYuaNm6xAu8tE/8ZXtDNh/JQXpF+GC7VlkU3C7wCLj0pS9orHolK641RewcIRgWhBajO1WcMeR9OZbe7eftFb99kbjWM3Q9ZaonxQJtcivlfnKhN49d6sZdmqlw+aEmJcxmNTCXvHg5ilNWj3Qy5jA4nx+/ylPgf11hoUkL3aXbEKwgip8lSk7lAdNN8ORw18s3l/7fQB8xN2U3AbSKiWAXDEkxO/ZXz636DB//O2ARWR1kpgaAtyPZNQAVac8rZyGPYM8X71PxbXfK+m9FMk0gS8IyCfuyQDWxQqgDxJ9DfnToC8fraiPUPsVd69VRXCK4QBvaVY6QlucILkcEkTE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
