travis:
  secure:
    BINSTAR_TOKEN: lC+H3iIl/Wq324dtkVMopUWZPNZz55ad/oBO4KDmI35/F9nzBbNfpHDGDZDL11fBYbZzPLNvag9uMXa8C39fb7DSCQHxrCiv9yP/1sRjrUeEbSGjzwtCcFG3vHMY0PWetfoZafF44QuOL4uhfwVaRS8tmS5ZfyayRGf8ERLJ+tChKM5AbR0wgKGbYtfxPyyqjRrshP/50U7xQgcQC1wNXjiXnMg1N8SbyuzKm1RIDFEtGWmKpime1FdteSalSKsyrFLDS63Q12LyY7ngSncQQ9I415mf+rDcZEVcKHd6vpoOERuCgILT7Dbk3fnzaB18RgEs3EREajpyf6xqBd+m6eAkQZk/8fPhHk15siD+XUcWQp6Oi+omZLro/b+6EZTg+Sxyh+kiCglLVyjIDo+RIhfMNrSYNv4RV7SS8HTNWfDX76Yrom+EQDCvavy9lM4ll7hOgvs/V36aNEEalgogu0WtmBEWuyf0ABXBozaN9Xdgs3XXiKe5GrlwqpaQji7hr2sUn3O0z09lDQnbILBnZiqQOU490f+cDXQ0GZbEdlpHlpHVLYwyC80r2fL3pYWaMLxkQdrw5foKlhs+51/Lhi9Wp91CFax/7flOxugZaxg6rG6rS0aFL5menUOZq8ES9l0R/YEdbma25lvTM233/kGs1OEDc/3LmfmwuyoHCRE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
