travis:
  secure:
    BINSTAR_TOKEN: CbfRLy98yw23OB30vYqhWpm8sQRrDdAEpmifzocwSqL1dPk0Lld+P/9QtGv+62bSpsOE8dtanVRqsi3lzNZ8VDIibccQFh6WbV4CexTCJvCRB5+W75spnsCYvOtmpUJbTxOdoIzfwzQvfFuW9eMKK8v2h7LRtS1h4cRE064D/ZlKqQVUr2975tRk5h5ApRiNTjVdMccHqE5/Ah5RALirRwI5b9eZdmQ3gxCv6skhtF58a023DrWMXJCmFMhYa8BiNV/NFp2TYG6fmSrkRVoBnUsSTfa8gWOAsxpoqBd4xmOLQ9P6jvh2ygA7FM//A9v6tvGMuMt5AjUVQf8nvd5lirU18sQ2ceQ0+gsx1qZszOJZK3+sGlTl4KcmXQjxXwfUXVLIl2E5zenDi8IoxaRnM6YskgOIsA/Z+uepHqzDfN48KuyFwuId3pVP7Oq0vVWqk2DOB32UPT/h2RsunagFT+bR5xDRz42Wkp1VLzMITaLPJt06hQZLY9pzfUQymudtCIOxLTtSSuA1OT8jkgVsTLmDEQR3/NnXNCj5mwmSbJz5FnKAUUtGyZ6RA3vN2M2G6BE3R0reiTjuqyYkzC08FD2YpJurhvXxRoKiP3le9hD2pW74PrU4FPAihUG/hkDomyHtFRBLNpuSk859T9nr4mL8/2WkISK3xl2bFy0TcS4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
