travis:
  secure:
    BINSTAR_TOKEN: PKSR3WWOeMg6lGdUuzh/scrjo09TM+ZvJpIP+mRT9xf/XeMgV+00hLj08rej4GeHLB7F6xTR6jBsxPjCMiw+x0e7e7c1N888Ypf7F6hqjoeAaO/Cdg/GZY1ch469wjmQ3ytWzgmdnvrujBkCjka6BezSRlnqu/mKEWPVjiSovrs+9dKtT02G8HLyH8WUQmjQK7FT/5asC1m1XkDpi9bBgyGjfUUm678TH10exY+RhQr3ubg+gqXPtwB4o6OSq3BnWQXfQqBqlab+pXDTP73pv+f52CA+/dqjOuQ+9YHQuMgTV7wHshGVE9n+HnR+P4xw4i0rkCfyq5EPZ05Sadh4Pg6TP0KfW7t2MEdQG8dWP3U3AeNIWoMJtp4apstFcjQd9/eXJ+nnZtMM14H0rb8BQ04ZtZAwGlZxX0n3nwJSm+sfu8s4UVKJkAx29Fzj16gzjRLj7VmbHdnVvGrlDV1vdYHNuUWnUxHsCSKrpW6J+ycmfuu/m7ZWBUBNFlL8sTMILOi5HH9RUAI9ITbySnX00a27Cq1hBcDQ0CbD/RnTTJBH42u0mKtf8UWwZ7WFE5xyP92izMi3+kGweHFM7aNIPwoJzzO2cfEU+TDpbX9X9XAZZIbzBJbrDaw24vtfmp3s2uatcdpcTywemq06owcvuvsQVtyWSyu4SAQ/SMTlKGo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
